### ISSUE TITLE
Backend JWT CR API Name Issue

### ISSUE THREAD

**Issue by Avishka-Shamendra** [wso2/docs-apk#280]
**Description:**
The documentation should clearly state that  the `name` field under `targetRef` in [1] must refer to the `name` of API resource not the `API Name`

   - For the following API
   ```
  NAME                                              API NAME          VERSION   CONTEXT                  ORGANIZATION   AGE
  94d7c3e725635a090a59e6a6bbb5fb877296d616        BackJwtTest2          3.14      /backTestCR/3.14       default        2m39s
  ```
  - The following doesn't work 
  
  ```
    apiVersion: dp.wso2.com/v1alpha1
    ......
      targetRef:
        group: dp.wso2.com
        kind: API
        name: BackJwtTest2
  ```
  
  - But the following works,
  
  ```
    apiVersion: dp.wso2.com/v1alpha1
    ......
      targetRef:
        group: dp.wso2.com
        kind: API
        name: 94d7c3e725635a090a59e6a6bbb5fb877296d616
  ```

[1] [Sample code snippet](https://apk.docs.wso2.com/en/latest/create-api/create-and-attach-api-policies/backend-jwt-token-manipulation/backend-jwt-token-manipulation-via-crs/#sample-code-snippet)
